doubles for precision windows
EoRImaging/fhdps_utils pull request #1
Opened 2019-06-28 07:13 UTC by nicholebarry

The current code creates spectral windows as floats. The resulting fft of a Blackman-Harris has sidelobe structure constrained at the float level

<img width="590" alt="Screen Shot 2019-06-28 at 5 08 50 pm" src="https://user-images.githubusercontent.com/5588290/60324277-c2f6b300-99c7-11e9-81fc-19def6c99596.png">

If we change it to double precision, it looks like this 
<img width="593" alt="Screen Shot 2019-06-28 at 5 07 53 pm" src="https://user-images.githubusercontent.com/5588290/60324310-d1dd6580-99c7-11e9-8593-0115b64cb24e.png">

Here is the difference PS between a float and double Blackman-Harris spectral window. The k0 has changed because the sidelobes affect the integral of the window, which is used to normalize.
![MWA_limit2019_fullimg_ch9-126_averemove_swbh_dencorr__btl_noalltv_noocc4_minus_btl_noalltv_noocc4_2dkpower](https://user-images.githubusercontent.com/5588290/60324392-02bd9a80-99c8-11e9-8c52-aab85afb5b99.png)

2019-07-03 18:34 UTC, mwilensky768 commented
Big difference in the window function! It looks like this makes a consistent difference in the dirty around the first coarse band line? Also slightly below that in the splotch there is consistently blue between polarizations.

2019-07-03 18:55 UTC, mwilensky768 reviewed
This change looks very straight-forward and I think the new code should be able to go straight through. I see there are some straggling `findgen` in the Tukey edge_length block.

This might be opening a can of worms, and maybe there is another forum where we should discuss this, but what is with the gymnastics involving `n_use`? Is this related to wanting a well-defined DC bin (It looks like you always want n_use to be odd)? The reason I ask is because it looks like the cosine terms in a Blackman-Harris window are conventionally defined such that you would divide by `n_use` in the argument, rather than `(n_use-1)`.

2019-07-03 20:09 UTC, bhazelton commented
Looks great! @mwilensky768 the `n_use` business is about the option to use a symmetric or periodic window when you have an even number of channels (see https://en.wikipedia.org/wiki/Window_function#Symmetry)

2019-07-03 20:10 UTC, bhazelton approved these changes
Looks good and straight-forward.

2019-07-03 20:13 UTC, bhazelton requested changes
Oh, just read Mike's comment more carefully -- The `findgen`s in the Tukey section should be updated. Good catch @mwilensky768

2020-02-17 01:24 UTC, nicholebarry commented
Implemented in master

2020-02-17 01:24 UTC, closed without merging